# Numpy Basic

In [1]:
import numpy as np

## data type

array의 dtype을 본다. 

In [70]:
arr = np.array([[1,2,3],[1,2,3]])
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [71]:
arr.dtype

dtype('int32')

.astype()으로 datatype을 변환 가능

In [73]:
arr = arr.astype('float32')

In [74]:
arr.dtype

dtype('float32')

In [75]:
arr = np.array([[1,2,3],[1,2,3]],dtype = np.uint8)
arr.dtype

dtype('uint8')

len(arr.shape) 를 통해서 차원의 갯수를 확인 할 수 있지만,  
아래와 같이 ndim을 통해 차원 수를 return 가능

In [76]:
arr.shape

(2, 3)

In [77]:
len(arr.shape)

2

size 확인

In [78]:
arr.size

6

# Reshape

In [79]:
arr.shape

(2, 3)

In [80]:
arr.reshape([1,6])

array([[1, 2, 3, 1, 2, 3]], dtype=uint8)

In [81]:
arr.shape

(2, 3)

In [82]:
arr = np.array([[1,2,3],[1,2,3]])

In [83]:
arr.reshape([6]).shape

(6,)

Reshape, -1 활용 #기본적으로 남는 차원을 다가져간다

In [84]:
arr = arr.reshape(-1)
arr.shape

(6,)

In [85]:
arr = arr.reshape(1,-1)
arr.shape

(1, 6)

random array 생성

In [87]:
arr = np.random.randn(8,8)
arr.shape

(8, 8)

In [91]:
arr = arr.reshape(1,-1)
arr.shape

(1, 64)

3차원으로 늘리기

In [93]:
arr= arr.reshape(-1,2,1)
arr.shape

(32, 2, 1)

## Ravel

arr의 차원을 1로 바꿔줌  

In [94]:
arr = arr.ravel()
arr.shape

(64,)

arr.reshape(-1) 와 같음

In [95]:
arr.ravel() == arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## np.expand_dims()

안의 값은 유지하되 차원 수를 늘리고 싶을 때가 있음  
이럴 때 사용하는 것이 expand_dims  

In [108]:
arr = arr.ravel()
arr.shape

(64,)

In [109]:
arr = np.expand_dims(arr,-1) #뒤에 차원 추가
arr.shape

(64, 1)

In [107]:
arr = np.expand_dims(arr,0) #앞에 차원 추가
arr.shape

(1, 64, 1)

## zeros & ones

0으로 채워진 numpy array를 만들 수 있음

In [3]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
zeros = np.zeros(1)
zeros

array([0.])

In [7]:
ones = np.ones([10,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
ones *5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [10]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [12]:
arr = np.arange(4,9)
arr

array([4, 5, 6, 7, 8])

In [14]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# index

In [17]:
nums = [1,2,3,4,5]
nums[2:]

[3, 4, 5]

In [18]:
arr[1]

array([3, 4, 5])

In [20]:
arr[1][2]

5

In [21]:
arr[1,2]

5

# Slicing

In [22]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [23]:
arr[1:,1:]

array([[4, 5],
       [7, 8]])

## boolean indexing

In [26]:
data = np.random.randn(3,3)
data

array([[ 0.57044615,  0.91554304, -0.13677076],
       [-1.31785562,  0.6629162 ,  0.53976575],
       [-0.35228852, -1.43715195,  1.09421791]])

In [27]:
data<=0

array([[False, False,  True],
       [ True, False, False],
       [ True,  True, False]])

In [32]:
data[data<=0] =1

In [33]:
data

array([[0.57044615, 0.91554304, 1.        ],
       [1.        , 0.6629162 , 0.53976575],
       [1.        , 1.        , 1.09421791]])

# Broadcast

broadcast는 연산 하려는 서로 다른 두개의 행렬의 shape가 같지 않고,  
한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때  
이를 여러 복사를 하여 연산을 함

In [37]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
arr+3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
arr*3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [40]:
arr + np.array([1,1,1])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr + np.array([1,2,3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

## Math Fuction

In [42]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [43]:
arr +arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [44]:
np.add(arr,1) # arr+1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr = np.random.randint(2,size=27).reshape(3,3,3)
arr_2 = np.random.randint(2,size=9).reshape(3,3)

In [47]:
arr.shape

(3, 3, 3)

In [48]:
arr

array([[[0, 0, 0],
        [0, 0, 1],
        [0, 1, 0]],

       [[0, 0, 0],
        [1, 0, 0],
        [1, 0, 1]],

       [[1, 0, 0],
        [1, 1, 0],
        [0, 0, 0]]])

In [49]:
arr_2

array([[1, 0, 0],
       [0, 1, 1],
       [0, 1, 1]])

In [50]:
arr +arr_2

array([[[1, 0, 0],
        [0, 1, 2],
        [0, 2, 1]],

       [[1, 0, 0],
        [1, 1, 1],
        [1, 1, 2]],

       [[2, 0, 0],
        [1, 2, 1],
        [0, 1, 1]]])

In [51]:
np.sum(arr)

8

In [52]:
np.sum(arr+arr_2)

23

In [54]:
np.max(arr + arr_2)

2

In [57]:
np.max(arr + arr_2,0)

array([[2, 0, 0],
       [1, 2, 2],
       [1, 2, 2]])

In [59]:
np.max(arr + arr_2,axis=-1)

array([[1, 2, 2],
       [1, 1, 2],
       [2, 2, 1]])

In [60]:
np.mean(arr)

0.2962962962962963

In [65]:
arr = np.array([1,222,2,5,3,4,6,7,9])

In [66]:
np.argmax(arr) # 제일큰 값 index번호

1

In [67]:
np.unique(arr)

array([  1,   2,   3,   4,   5,   6,   7,   9, 222])